create table blog_categories (
  id integer generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint blog_categories_slug_format
    check (slug ~ '^[a-z0-9][a-z0-9-]*$')
);

create table blog_tags (
  id integer generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  created_at timestamptz not null default now(),
  constraint blog_tags_slug_format
    check (slug ~ '^[a-z0-9][a-z0-9-]*$')
);

create table blog_posts (
  id integer generated by default as identity primary key,
  published_number integer unique,
  legacy_slug text unique,
  title text not null,
  description text not null default '',
  excerpt text not null default '',
  body_markdown text not null,
  extension text not null default 'md',
  status text not null default 'draft',
  author text not null,
  category_id integer not null references blog_categories(id),
  published_at date,
  updated_at date,
  original_url text,
  cover_image_url text,
  embedded_pdf_url text,
  allow_pdf_download boolean not null default true,
  created_at timestamptz not null default now(),
  modified_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint blog_posts_status_check
    check (status in ('draft', 'published', 'archived')),
  constraint blog_posts_published_number_positive
    check (published_number is null or published_number > 0),
  constraint blog_posts_published_requires_number
    check (status <> 'published' or published_number is not null),
  constraint blog_posts_extension_check
    check (extension in ('md', 'mdx'))
);

create index blog_posts_status_published_at_idx
  on blog_posts (status, published_at desc);

create index blog_posts_category_status_idx
  on blog_posts (category_id, status);

create table blog_post_tags (
  post_id integer not null references blog_posts(id) on delete cascade,
  tag_id integer not null references blog_tags(id),
  primary key (post_id, tag_id)
);

create index blog_post_tags_tag_id_idx
  on blog_post_tags (tag_id);

create table blog_post_revisions (
  id integer generated by default as identity primary key,
  post_id integer not null references blog_posts(id) on delete cascade,
  title text not null,
  body_markdown text not null,
  snapshot jsonb not null,
  reason text not null default 'manual',
  created_at timestamptz not null default now(),
  constraint blog_post_revisions_reason_check
    check (reason in ('manual', 'publish'))
);

create index blog_post_revisions_post_created_idx
  on blog_post_revisions (post_id, created_at desc);

create table blog_post_assets (
  id integer generated by default as identity primary key,
  post_id integer not null references blog_posts(id) on delete cascade,
  asset_id uuid not null references media_assets(id),
  role text not null default 'attachment',
  sort_order integer not null default 0,
  unique (post_id, asset_id, role),
  constraint blog_post_assets_role_check
    check (role in ('cover', 'inline', 'attachment', 'embedded_pdf'))
);

insert into blog_categories (slug, name, sort_order)
values
  ('backend', 'Backend', 10),
  ('database', 'Database', 20),
  ('git', 'Git', 30),
  ('java', 'Java', 40),
  ('opensource', 'Open Source', 50),
  ('portfolio', 'Portfolio', 60),
  ('web', 'Web', 70),
  ('uncategorized', 'Uncategorized', 999)
on conflict (slug) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order;

alter table blog_categories enable row level security;
alter table blog_tags enable row level security;
alter table blog_posts enable row level security;
alter table blog_post_tags enable row level security;
alter table blog_post_revisions enable row level security;
alter table blog_post_assets enable row level security;
